import {
    Event,
    EventCategory,
    User,
    Registration,
    Review,
    Badge
} from '@/types';
import { addDays, subDays } from 'date-fns';

export const mockCategories: EventCategory[] = [
    'Academic',
    'Sports',
    'Cultural',
    'Tech',
    'Workshop',
    'Social',
    'Career',
    'Health'
];

export const mockBadges: Badge[] = [
    {
        id: 'b1',
        name: 'Early Bird',
        description: 'Registered for 5 events early',
        icon: 'bird',
        condition: 'Register 5 times',
        rarity: 'common',
        earnedAt: subDays(new Date(), 10)
    },
    {
        id: 'b2',
        name: 'Social Butterfly',
        description: 'Attended 10 social events',
        icon: 'butterfly',
        condition: 'Attend 10 social events',
        rarity: 'rare',
        earnedAt: subDays(new Date(), 2)
    }
];

export const mockUser: User = {
    id: 'u1',
    email: 'arjun.sharma@college.edu',
    name: 'Arjun Sharma',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arjun',
    interests: ['Tech', 'Sports', 'Career'],
    collegeName: 'Mumbai University',
    year: '3rd Year',
    department: 'Computer Science',
    points: 450,
    badges: mockBadges,
    role: 'student',
    createdAt: subDays(new Date(), 365)
};

const organizerUser: User = {
    id: 'o1',
    email: 'events@college.edu',
    name: 'Event Committee',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Committee',
    interests: [],
    collegeName: 'Mumbai University',
    points: 1000,
    badges: [],
    role: 'organizer',
    createdAt: subDays(new Date(), 700)
};

export const mockEvents: any[] = [
    {
        id: 'e1',
        title: 'AI & Machine Learning Workshop',
        description: 'A comprehensive workshop on the fundamentals of AI and ML with hands-on projects using Python and TensorFlow.',
        image: 'https://images.unsplash.com/photo-1555255707-c07966088b7b?q=80&w=1632&auto=format&fit=crop',
        category: 'Tech',
        date: addDays(new Date(), 2),
        time: '10:00 AM',
        duration: '4 hours',
        location: 'Computer Lab 3, Watson Block',
        coordinates: { lat: 19.0760, lng: 72.8777 },
        price: 0,
        capacity: 60,
        registeredCount: 45,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['AI', 'ML', 'Python', 'Workshop'],
        popularityScore: 92,
        viewCount: 1250,
        createdAt: subDays(new Date(), 5),
        updatedAt: subDays(new Date(), 1)
    },
    {
        id: 'e2',
        title: 'Annual Sports Day 2026',
        description: 'Join us for a day of competitive sports, team spirit, and fun. Events include cricket, football, athletics, and more.',
        image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?q=80&w=1470&auto=format&fit=crop',
        category: 'Sports',
        date: addDays(new Date(), 14),
        time: '08:00 AM',
        duration: '8 hours',
        location: 'Main College Ground',
        coordinates: { lat: 19.0720, lng: 72.8750 },
        price: 0,
        capacity: 500,
        registeredCount: 320,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Sports', 'Competition', 'Fun'],
        popularityScore: 98,
        viewCount: 3400,
        createdAt: subDays(new Date(), 20),
        updatedAt: subDays(new Date(), 2)
    },
    {
        id: 'e3',
        title: 'Cultural Night: Festival of Colors',
        description: 'Celebrate the vibrant culture with dance, music, and colors. A night to remember with DJ and live performances.',
        image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1470&auto=format&fit=crop',
        category: 'Cultural',
        date: addDays(new Date(), 10),
        time: '06:00 PM',
        duration: '5 hours',
        location: 'Open Air Amphitheatre',
        coordinates: { lat: 19.0800, lng: 72.8800 },
        price: 100,
        capacity: 400,
        registeredCount: 350,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Dance', 'Music', 'Festival', 'Party'],
        popularityScore: 95,
        viewCount: 2800,
        createdAt: subDays(new Date(), 15),
        updatedAt: subDays(new Date(), 3)
    },
    {
        id: 'e4',
        title: 'Startup Pitch Competition',
        description: 'Pitch your startup idea to a panel of investors and industry experts. Win cash prizes and mentorship opportunities.',
        image: 'https://images.unsplash.com/photo-1559136555-930b7a4754a4?q=80&w=1632&auto=format&fit=crop',
        category: 'Career',
        date: addDays(new Date(), 25),
        time: '02:00 PM',
        duration: '4 hours',
        location: 'Auditorium Hall A',
        coordinates: { lat: 19.0740, lng: 72.8720 },
        price: 200,
        capacity: 100,
        registeredCount: 60,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Startup', 'Business', 'Pitch', 'Entrepreneurship'],
        popularityScore: 88,
        viewCount: 1500,
        createdAt: subDays(new Date(), 10),
        updatedAt: subDays(new Date(), 1)
    },
    {
        id: 'e5',
        title: 'Yoga & Meditation Session',
        description: 'Relax and rejuvenate with a guided yoga and meditation session. Suitable for all levels. Mats provided.',
        image: 'https://images.unsplash.com/photo-1544367563-121910aa662f?q=80&w=1476&auto=format&fit=crop',
        category: 'Health',
        date: addDays(new Date(), 5),
        time: '07:00 AM',
        duration: '1.5 hours',
        location: 'College Gym Terrace',
        coordinates: { lat: 19.0770, lng: 72.8790 },
        price: 0,
        capacity: 40,
        registeredCount: 35,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Yoga', 'Wellness', 'Health', 'Meditation'],
        popularityScore: 82,
        viewCount: 900,
        createdAt: subDays(new Date(), 8),
        updatedAt: subDays(new Date(), 2)
    },
    {
        id: 'e6',
        title: 'Coding Hackathon 48hrs',
        description: 'Build innovative solutions in 48 hours. Themes include Sustainability, EdTech, and FinTech. Great prizes to be won!',
        image: 'https://images.unsplash.com/photo-1504384308090-c54be3852f92?q=80&w=1470&auto=format&fit=crop',
        category: 'Tech',
        date: addDays(new Date(), 30),
        time: '09:00 AM',
        duration: '48 hours',
        location: 'Technology Block, Labs 1-4',
        coordinates: { lat: 19.0755, lng: 72.8760 },
        price: 500,
        capacity: 200,
        registeredCount: 150,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Hackathon', 'Coding', 'Innovation', 'Competition'],
        popularityScore: 97,
        viewCount: 5000,
        createdAt: subDays(new Date(), 25),
        updatedAt: subDays(new Date(), 5)
    },
    {
        id: 'e7',
        title: 'Drama Club Performance',
        description: 'Presenting "The Merchant of Venice" - a classic play performed by our talented drama club members.',
        image: 'https://images.unsplash.com/photo-1507676184212-d0378b20db0d?q=80&w=1470&auto=format&fit=crop',
        category: 'Cultural',
        date: addDays(new Date(), 12),
        time: '05:30 PM',
        duration: '2.5 hours',
        location: 'Main Auditorium',
        coordinates: { lat: 19.0760, lng: 72.8777 },
        price: 500, // Changed to paid for testing
        capacity: 200,
        registeredCount: 180,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Drama', 'Theatre', 'Art', 'Play'],
        popularityScore: 85,
        viewCount: 1200,
        createdAt: subDays(new Date(), 12),
        updatedAt: subDays(new Date(), 4)
    },
    {
        id: 'e8',
        title: 'Career Fair 2026',
        description: 'Meet recruiters from top companies including Google, Microsoft, TCS, and more. Bring your resumes!',
        image: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?q=80&w=1374&auto=format&fit=crop',
        category: 'Career',
        date: addDays(new Date(), 40),
        time: '10:00 AM',
        duration: '6 hours',
        location: 'Convention Center',
        price: 0,
        capacity: 1000,
        registeredCount: 800,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Jobs', 'Internships', 'Networking', 'Career'],
        popularityScore: 99,
        viewCount: 6000,
        createdAt: subDays(new Date(), 30),
        updatedAt: subDays(new Date(), 1)
    },
    {
        id: 'e9',
        title: 'Photography Workshop',
        description: 'Learn the basics of DSLR photography, lighting, and composition from professional photographer Ravi Verma.',
        image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=1638&auto=format&fit=crop',
        category: 'Workshop',
        date: addDays(new Date(), 8),
        time: '11:00 AM',
        duration: '3 hours',
        location: 'Media Room 2',
        price: 150,
        capacity: 30,
        registeredCount: 25,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Photography', 'Art', 'Skills'],
        popularityScore: 78,
        viewCount: 800,
        createdAt: subDays(new Date(), 6),
        updatedAt: subDays(new Date(), 2)
    },
    {
        id: 'e10',
        title: 'Freshers Intro Party',
        description: 'Welcome party for the new batch! Music, games, snacks, and a chance to make new friends.',
        image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=1470&auto=format&fit=crop',
        category: 'Social',
        date: addDays(new Date(), 3),
        time: '07:00 PM',
        duration: '4 hours',
        location: 'College Cafeteria',
        price: 250,
        capacity: 150,
        registeredCount: 140,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Party', 'Social', 'Freshers', 'Fun'],
        popularityScore: 94,
        viewCount: 2100,
        createdAt: subDays(new Date(), 14),
        updatedAt: subDays(new Date(), 3)
    },
    {
        id: 'e11',
        title: 'Exam Prep Strategy Session',
        description: 'Get tips and strategies from toppers on how to ace your upcoming semester exams.',
        image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=1470&auto=format&fit=crop',
        category: 'Academic',
        date: addDays(new Date(), 18),
        time: '04:00 PM',
        duration: '2 hours',
        location: 'Seminar Hall 1',
        price: 0,
        capacity: 100,
        registeredCount: 90,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Study', 'Exams', 'Academic', 'Tips'],
        popularityScore: 86,
        viewCount: 1100,
        createdAt: subDays(new Date(), 5),
        updatedAt: subDays(new Date(), 1)
    },
    {
        id: 'e12',
        title: 'Inter-College Debate Competition',
        description: 'A battle of wits and words. Topic: "AI: Boon or Bane for Humanity?" Open to all departments.',
        image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=1470&auto=format&fit=crop',
        category: 'Academic',
        date: addDays(new Date(), 22),
        time: '10:00 AM',
        duration: '4 hours',
        location: 'Conference Room B',
        price: 0,
        capacity: 80,
        registeredCount: 40,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Debate', 'Speaking', 'Competition', 'Academic'],
        popularityScore: 75,
        viewCount: 600,
        createdAt: subDays(new Date(), 10),
        updatedAt: subDays(new Date(), 2)
    },
    {
        id: 'e13',
        title: 'Mental Health Awareness Seminar',
        description: 'Expert psychologists discuss stress management and mental well-being for students.',
        image: 'https://images.unsplash.com/photo-1527689368864-3a821dbccc34?q=80&w=1470&auto=format&fit=crop',
        category: 'Health',
        date: addDays(new Date(), 7),
        time: '03:00 PM',
        duration: '2 hours',
        location: 'Auditorium Hall B',
        price: 0,
        capacity: 200,
        registeredCount: 120,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Mental Health', 'Wellness', 'Seminar'],
        popularityScore: 89,
        viewCount: 1400,
        createdAt: subDays(new Date(), 7),
        updatedAt: subDays(new Date(), 1)
    },
    {
        id: 'e14',
        title: 'Robotics Workshop: Build Your Bot',
        description: 'Hands-on workshop to build a line-following robot using Arduino. Components will be provided.',
        image: 'https://images.unsplash.com/photo-1561557944-6e7860d1a7eb?q=80&w=1374&auto=format&fit=crop',
        category: 'Tech',
        date: addDays(new Date(), 15),
        time: '11:00 AM',
        duration: '5 hours',
        location: 'Electronics Lab',
        price: 300,
        capacity: 40,
        registeredCount: 38,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Robotics', 'Arduino', 'Tech', 'Workshop'],
        popularityScore: 91,
        viewCount: 1800,
        createdAt: subDays(new Date(), 12),
        updatedAt: subDays(new Date(), 2)
    },
    {
        id: 'e15',
        title: 'Stand-up Comedy Night',
        description: 'Laugh out loud with top college comedians and a guest performance by a local stand-up artist.',
        image: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?q=80&w=1470&auto=format&fit=crop',
        category: 'Cultural',
        date: addDays(new Date(), 28),
        time: '07:30 PM',
        duration: '2 hours',
        location: 'Open Air Amphitheatre',
        price: 100,
        capacity: 350,
        registeredCount: 290,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Comedy', 'Fun', 'Entertainment'],
        popularityScore: 93,
        viewCount: 2200,
        createdAt: subDays(new Date(), 18),
        updatedAt: subDays(new Date(), 3)
    },
    {
        id: 'e16',
        title: 'Effective Communication Skills',
        description: 'Workshop on improving public speaking and interpersonal communication skills for career success.',
        image: 'https://images.unsplash.com/photo-1552581234-26160f608093?q=80&w=1470&auto=format&fit=crop',
        category: 'Workshop',
        date: addDays(new Date(), 6),
        time: '02:00 PM',
        duration: '3 hours',
        location: 'Seminar Hall 2',
        price: 50,
        capacity: 60,
        registeredCount: 45,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Communication', 'Soft Skills', 'Career'],
        popularityScore: 80,
        viewCount: 750,
        createdAt: subDays(new Date(), 5),
        updatedAt: subDays(new Date(), 1)
    },
    {
        id: 'e17',
        title: 'Badminton Tournament',
        description: 'Inter-department badminton singles and doubles tournament. Register now to participate!',
        image: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?q=80&w=1470&auto=format&fit=crop',
        category: 'Sports',
        date: addDays(new Date(), 20),
        time: '09:00 AM',
        duration: '6 hours',
        location: 'Indoor Sports Complex',
        price: 150,
        capacity: 64,
        registeredCount: 50,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Badminton', 'Sports', 'Competition'],
        popularityScore: 87,
        viewCount: 1300,
        createdAt: subDays(new Date(), 15),
        updatedAt: subDays(new Date(), 2)
    },
    {
        id: 'e18',
        title: 'Blood Donation Camp',
        description: 'Donate blood and save lives. Organized in collaboration with Red Cross Society.',
        image: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?q=80&w=1383&auto=format&fit=crop',
        category: 'Health',
        date: addDays(new Date(), 11),
        time: '10:00 AM',
        duration: '5 hours',
        location: 'Student Center Lounge',
        price: 0,
        capacity: 200,
        registeredCount: 85,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Charity', 'Health', 'Community'],
        popularityScore: 90,
        viewCount: 1600,
        createdAt: subDays(new Date(), 10),
        updatedAt: subDays(new Date(), 1)
    },
    {
        id: 'e19',
        title: 'Cybersecurity Basics',
        description: 'Learn how to protect yourself online and understand the basics of ethical hacking.',
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=1470&auto=format&fit=crop',
        category: 'Tech',
        date: addDays(new Date(), 16),
        time: '04:30 PM',
        duration: '2 hours',
        location: 'Computer Lab 1',
        price: 0,
        capacity: 80,
        registeredCount: 75,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Security', 'Tech', 'Hacking', 'Cyber'],
        popularityScore: 88,
        viewCount: 1900,
        createdAt: subDays(new Date(), 12),
        updatedAt: subDays(new Date(), 3)
    },
    {
        id: 'e20',
        title: 'Music Club Jam Session',
        description: 'Open mic jam session for all musicians and singers. Bring your instruments!',
        image: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?q=80&w=1470&auto=format&fit=crop',
        category: 'Social',
        date: addDays(new Date(), 9),
        time: '06:00 PM',
        duration: '3 hours',
        location: 'Music Room',
        price: 0,
        capacity: 50,
        registeredCount: 40,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Music', 'Jam', 'Social', 'Fun'],
        popularityScore: 84,
        viewCount: 850,
        createdAt: subDays(new Date(), 8),
        updatedAt: subDays(new Date(), 1)
    },
    {
        id: 'e21',
        title: 'LinkedIn Optimization',
        description: 'Workshop on creating a professional LinkedIn profile to attract recruiters and build your network.',
        image: 'https://images.unsplash.com/photo-1611944212129-2999044c238c?q=80&w=1470&auto=format&fit=crop',
        category: 'Career',
        date: addDays(new Date(), 13),
        time: '03:00 PM',
        duration: '1.5 hours',
        location: 'Online (Zoom)',
        price: 0,
        capacity: 500,
        registeredCount: 300,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Career', 'LinkedIn', 'Profile', 'Networking'],
        popularityScore: 92,
        viewCount: 2500,
        createdAt: subDays(new Date(), 10),
        updatedAt: subDays(new Date(), 2)
    },
    {
        id: 'e22',
        title: 'Painting Workshop: Watercolors',
        description: 'Relaxing painting session for beginners. All art supplies will be provided.',
        image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?q=80&w=1480&auto=format&fit=crop',
        category: 'Workshop',
        date: addDays(new Date(), 21),
        time: '11:00 AM',
        duration: '3 hours',
        location: 'Art Studio',
        price: 200,
        capacity: 25,
        registeredCount: 20,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Art', 'Painting', 'Creativity'],
        popularityScore: 79,
        viewCount: 650,
        createdAt: subDays(new Date(), 15),
        updatedAt: subDays(new Date(), 3)
    },
    {
        id: 'e23',
        title: 'Science Exhibition 2026',
        description: 'Showcasing innovative science projects by students from various departments.',
        image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?q=80&w=1470&auto=format&fit=crop',
        category: 'Academic',
        date: addDays(new Date(), 35),
        time: '09:30 AM',
        duration: '7 hours',
        location: 'Main Hall',
        price: 0,
        capacity: 1000,
        registeredCount: 450,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Science', 'Exhibition', 'Projects', 'Academic'],
        popularityScore: 90,
        viewCount: 3100,
        createdAt: subDays(new Date(), 25),
        updatedAt: subDays(new Date(), 5)
    },
    {
        id: 'e24',
        title: 'Fitness Bootcamp',
        description: 'High-intensity interval training (HIIT) session for fitness enthusiasts.',
        image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1470&auto=format&fit=crop',
        category: 'Health',
        date: addDays(new Date(), 4),
        time: '06:30 AM',
        duration: '1 hour',
        location: 'College Ground',
        price: 50,
        capacity: 40,
        registeredCount: 30,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Fitness', 'Workout', 'Health', 'Bootcamp'],
        popularityScore: 81,
        viewCount: 700,
        createdAt: subDays(new Date(), 4),
        updatedAt: subDays(new Date(), 1)
    },
    {
        id: 'e25',
        title: 'Chess Championship',
        description: 'Rapid chess tournament. Prove your strategic skills and win the college championship trophy.',
        image: 'https://images.unsplash.com/photo-1586165368502-1bad197a6461?q=80&w=1558&auto=format&fit=crop',
        category: 'Sports',
        date: addDays(new Date(), 26),
        time: '10:00 AM',
        duration: '5 hours',
        location: 'Library Reading Room',
        price: 100,
        capacity: 64,
        registeredCount: 55,
        organizerId: 'o1',
        organizer: organizerUser,
        status: 'published',
        tags: ['Chess', 'Strategy', 'Game', 'Competition'],
        popularityScore: 85,
        viewCount: 1150,
        createdAt: subDays(new Date(), 20),
        updatedAt: subDays(new Date(), 2)
    }
];

export const mockRegistrations: Registration[] = [
    {
        id: 'r1',
        userId: 'u1',
        eventId: 'e1',
        status: 'registered',
        registeredAt: subDays(new Date(), 3),
        attended: false,
        reminderSent: false,
        qrCode: 'qr-code-string-123'
    },
    {
        id: 'r2',
        userId: 'u1',
        eventId: 'e5',
        status: 'registered',
        registeredAt: subDays(new Date(), 1),
        attended: false,
        reminderSent: true,
        qrCode: 'qr-code-string-456'
    },
    {
        id: 'r3',
        userId: 'u1',
        eventId: 'e7',
        status: 'waitlist',
        registeredAt: subDays(new Date(), 5),
        attended: false,
        reminderSent: false
    },
    {
        id: 'r4',
        userId: 'u1',
        eventId: 'e2',
        status: 'registered',
        registeredAt: subDays(new Date(), 10),
        attended: false,
        reminderSent: false,
        qrCode: 'qr-code-string-789'
    },
    {
        id: 'r5',
        userId: 'u1',
        eventId: 'e10',
        status: 'cancelled',
        registeredAt: subDays(new Date(), 12),
        attended: false,
        reminderSent: false
    }
];

export const mockReviews: Review[] = [
    {
        id: 'rv1',
        userId: 'u2',
        user: { ...mockUser, id: 'u2', name: 'Priya Patel', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya' },
        eventId: 'e1',
        rating: 5,
        comment: 'Amazing workshop! The instructor was very knowledgeable and the hands-on projects were great.',
        createdAt: subDays(new Date(), 1),
        helpfulCount: 12
    },
    {
        id: 'rv2',
        userId: 'u3',
        user: { ...mockUser, id: 'u3', name: 'Rahul Gupta', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rahul' },
        eventId: 'e1',
        rating: 4,
        comment: 'Good content, but the pace was a bit fast for beginners. Overall very informative.',
        createdAt: subDays(new Date(), 1),
        helpfulCount: 5
    },
    {
        id: 'rv3',
        userId: 'u4',
        user: { ...mockUser, id: 'u4', name: 'Sneha Reddy', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sneha' },
        eventId: 'e2',
        rating: 5,
        comment: 'Best sports day ever! The organization was top notch.',
        createdAt: subDays(new Date(), 10),
        helpfulCount: 20
    },
    {
        id: 'rv4',
        userId: 'u5',
        user: { ...mockUser, id: 'u5', name: 'Vikram Singh', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Vikram' },
        eventId: 'e5',
        rating: 3,
        comment: 'Nice session but it started 15 minutes late.',
        createdAt: subDays(new Date(), 2),
        helpfulCount: 2
    },
    {
        id: 'rv5',
        userId: 'u6',
        user: { ...mockUser, id: 'u6', name: 'Ananya Das', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ananya' },
        eventId: 'e7',
        rating: 5,
        comment: 'The performance was breathtaking. Kudus to the drama team!',
        createdAt: subDays(new Date(), 5),
        helpfulCount: 8
    }
];

// Utility functions
export const getEventById = (id: string): Event | undefined => {
    return mockEvents.find(event => event.id === id);
};

export const getEventsByCategory = (category: EventCategory): Event[] => {
    return mockEvents.filter(event => event.category === category);
};

export const getUpcomingEvents = (): Event[] => {
    const now = new Date();
    return mockEvents.filter(event => new Date(event.date) >= now).sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
};

export const getTrendingEvents = (category?: string): Event[] => {
    let events = [...mockEvents];
    if (category && category !== 'all') {
        events = events.filter(e => e.category.toLowerCase() === category.toLowerCase());
    }
    return events.sort((a, b) => b.popularityScore - a.popularityScore).slice(0, 5);
};

export const getUserRegistrations = (userId: string): Registration[] => {
    return mockRegistrations.filter(reg => reg.userId === userId);
};
